services:
  kash:
    build: .
    container_name: kash
    ports:
      - "8200:8200"
    environment:
      - TZ=America/Caracas
      - DB_HOST=postgres_central
      - DB_PORT=5432
      - DB_NAME=kash
      - DB_USER=admin_root
      - DB_PASSWORD=cattivellio_master
      - SESSION_SECRET=change-me-to-a-random-string
    restart: unless-stopped

networks:
  default:
    name: postgree_red_central_db
    external: true
